language: python
python:
- '2.6'
- '2.7'
install:
- pip install pytest-cov
- pip install pytest-pep8
- python setup.py install
script: py.test test/unit/ --doctest-modules -v --cov kalibrate --cov-report term-missing
after_success: -coveralls
deploy:
  provider: pypi
  user: ashmastaflash
  password:
    secure: Ja2jW3e56U+27yzyekoiqbwQ0lycZRXryC0GCIDuTsPm1tCmATsdJS7LYYIusSNOFZUd2Qr1GHr6Kp56/gjlyzttvcpHBFhhBKNVh5a0B5CDE2V4zBfUSiIazQm3oIxC0PmVW6Jo8iGTXug1H+1n/T3yBt5hpq5PO1QbHVkZq08+mZJ6+YBjv5uYW2H/H9+dO+PIv2/3FKwFaAh5LASDmPSjJhohgAtMTW9d9FBn1KRsBgVWQbEI/bEHG2ue1DnvU3+p0iBhIzW/cGYhwAzq3hNcbMhoKKOh6ttIyJO3cvcso63UBqJl33okP5wsIoIMkgp+ZUvGRfdfPuWT2jvDLYCnO2pfRukz4VyHzxP/LuhzrJ3E4BXC6ydGNMnpBUa2rDxQU0QlJ92w7PAOSbm5aqwYZ18c8baU89kiCLcPnHo1PT5sNLIgZOTZwsh/9qlg591RWEgOo1DvcArTatRsnPxI1IQiw51Rwg+to3KKbxjHVXT4ipZn4+LLe8d+O0jK/LJPa+dEHjJRIxyq8hrupkJxE8esPtj2Le2Xe5uTSvspvp3qw+ZCOvIseVYwVpfm4ORlG+TUleBlk+dmcFtIluANlU6v5Yv0cvE3/cb0AJggiFq8sAqeSoBEvP/9zdzHzAWt5SfeZAlKR+McGWLZLCuS+RCPBas/w27n7WW2Fto=
  on:
    tags: true
    repo: ashmastaflash/kal-wrapper
